version: '3'

networks:
  net:
    driver: bridge

volumes:
  images:

services:

  minio:
    depends_on:
      - rabbitmq
    image: minio:latest
    build:
      context: .
      dockerfile: minio.Dockerfile 
    container_name: 'minio'
    hostname: minio 
    expose:
      - "9000"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minio}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-miniosecretkey}
    networks:
     - net 
    command: server /data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    hostname: rabbitmq  # See https://hub.docker.com/_/rabbitmq/
    expose:
      - "5672"
      - "15672"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - net 
    tmpfs:
      - /var/lib/rabbitmq
    volumes:
      - /etc/rabbitmq
    read_only: true

  manager:
     image: manager 
     container_name: 'manager'
     networks:
       - net
     build:
       context: .
       dockerfile: manager.Dockerfile 
     volumes:
       - images:/images
       - "/var/run/docker.sock:/var/run/docker.sock" 
     restart: always
     command: ["sleep","infinity"] 

  upscaler:
     image: upscaler
     container_name: 'upscaler'
     networks:
       - net 
     build:  
       context: .
       dockerfile: upscaler.Dockerfile 
     restart: always
     command: ["sleep","infinity"]
     volumes:
      - images:/images
     ports:  
       - "5555:22"

